# Generated by Django 4.0.5 on 2022-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='published_date'),
        ),
    ]
