# Generated by Django 4.0.5 on 2022-07-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agora', '0002_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ManyToManyField(default=1, to='virtual_agora.theme'),
        ),
    ]
